--E1에서 출력할 행들 다 뽑아내고 E2 테이블에서 맞는 조건들은 다 명시
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
           E2.EMPNO AS MGR_EMPNO,
           E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+)
ORDER BY E1.EMPNO;

--E2에서 출력할 행들 다 뽑아내고 E1 테이블에서 맞는 조건들은 다 명시
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
           E2.EMPNO AS MGR_EMPNO,
           E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO
ORDER BY E1.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
           DEPTNO, D.DNAME, D.LOC
FROM EMP E JOIN DEPT D USING (DEPTNO)
WHERE SAL >= 3000
    AND E.MGR IS NOT NULL
ORDER BY DEPTNO, E.EMPNO;

--1
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
    AND E.SAL > 2000
ORDER BY D.DEPTNO, E.EMPNO;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
WHERE E.SAL > 2000
ORDER BY D.DEPTNO, E.EMPNO;

--2
SELECT D.DEPTNO, D.DNAME,
           TRUNC(AVG(E.SAL)) AS AVG_SAL,
           MAX(E.SAL) AS MAX_SAL,
           MIN(E.SAL) AS MIN_SAL,
           COUNT(*) AS CNT
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

SELECT D.DEPTNO, D.DNAME,
           TRUNC(AVG(E.SAL)) AS AVG_SAL,
           MAX(E.SAL) AS MAX_SAL,
           MIN(E.SAL) AS MIN_SAL,
           COUNT(*) AS CNT
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
GROUP BY D.DEPTNO, D.DNAME;

--3
SELECT D.DEPTNO, D.DNAME,
           E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO(+) = D.DEPTNO
ORDER BY D.DEPTNO, E.ENAME;

SELECT D.DEPTNO, D.DNAME,
           E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E RIGHT OUTER JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
ORDER BY D.DEPTNO, E.ENAME;

--4
SELECT D.DEPTNO, D.DNAME,
           E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO,
           S.LOSAL, S.HISAL, S.GRADE,
           M.EMPNO AS MGR_EMPNO, M.ENAME AS MGR_ENAME
FROM DEPT D, EMP E, SALGRADE S, EMP M
WHERE D.DEPTNO = E.DEPTNO(+)
    AND E.MGR = M.EMPNO(+)
    AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
ORDER BY D.DEPTNO, E.EMPNO;

SELECT D.DEPTNO, D.DNAME,
           E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO,
           S.LOSAL, S.HISAL, S.GRADE,
           M.EMPNO AS MGR_EMPNO, M.ENAME AS MGR_ENAME
FROM DEPT D LEFT OUTER JOIN EMP E ON (D.DEPTNO = E.DEPTNO)
                    LEFT OUTER JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
                    LEFT OUTER JOIN EMP M ON (E.MGR = M.EMPNO)
ORDER BY D.DEPTNO, E.EMPNO;