--데이터 사전
SELECT *
FROM DICTIONARY;

SELECT TABLE_NAME
FROM USER_TABLES;

SELECT *
FROM USER_TABLES;

SELECT OWNER, TABLE_NAME
FROM ALL_TABLES;

SELECT *
FROM ALL_TABLES;

--INDEX
SELECT *
FROM USER_INDEXES;

SELECT *
FROM USER_IND_COLUMNS;

CREATE INDEX IDX_EMP_SAL
    ON EMP (SAL);

SELECT *
FROM USER_IND_COLUMNS
WHERE INDEX_NAME = 'IDX_EMP_SAL';

DROP INDEX IDX_EMP_SAL;

--VIEW
SELECT EMPNO, ENAME, JOB, DEPTNO
FROM EMP
WHERE DEPTNO = 20;

CREATE VIEW VM_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
         FROM EMP
         WHERE DEPTNO = 20);

SELECT *
FROM VM_EMP20;

DROP VIEW VM_EMP20;

SELECT ROWNUM, E.*
FROM EMP E;

SELECT ROWNUM, E.*
FROM EMP E
ORDER BY SAL DESC;

SELECT ROWNUM, E.*
FROM (SELECT *
          FROM EMP E
          ORDER BY SAL DESC) E;

WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
FROM E;

SELECT ROWNUM, E.*
FROM (SELECT *
          FROM EMP E
          ORDER BY SAL DESC) E
WHERE ROWNUM <= 3;

WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
FROM E
WHERE ROWNUM <= 3;

--SEQUENCE
CREATE TABLE DEPT_SEQUENCE
    AS SELECT * FROM DEPT WHERE 1<>1;
   
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2;

INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
    VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT *
FROM DEPT_SEQUENCE
ORDER BY DEPTNO;

SELECT SEQ_DEPT_SEQUENCE.CURRVAL
FROM DUAL;

ALTER SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 3
    MAXVALUE 99
    CYCLE;

INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
    VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

DROP SEQUENCE SEQ_DEPT_SEQUENCE;

--SYNONYM
CREATE SYNONYM E
    FOR EMP;

SELECT *
FROM E;

DROP SYNONYM E;


--1
CREATE TABLE EMPIDX
    AS SELECT * FROM EMP;

CREATE INDEX IDX_EMPIDX_EMPNO
    ON EMPIDX (EMPNO);

SELECT *
FROM USER_INDEXES
WHERE INDEX_NAME = 'IDX_EMPIDX_EMPNO';

--2
CREATE OR REPLACE VIEW EMPIDX_OVER15K
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL,
                    CASE
                        WHEN COMM IS NULL THEN 'X'
                        ELSE 'O'
                    END AS COMM
          FROM EMPIDX
          WHERE SAL > 1500);

SELECT *
FROM EMPIDX_OVER15K;

--3
CREATE TABLE DEPTSEQ
    AS (SELECT * FROM DEPT);

CREATE SEQUENCE SEQ_DEPTSEQ
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE

INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC)
    VALUES(SEQ_DEPTSEQ.NEXTVAL, 'DATABASE', 'SEOUL');
    
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC)
    VALUES(SEQ_DEPTSEQ.NEXTVAL, 'WEB', 'BUSAN');
    
INSERT INTO DEPTSEQ (DEPTNO, DNAME, LOC)
    VALUES(SEQ_DEPTSEQ.NEXTVAL, 'MOBILE', 'ILSAN');

SELECT * FROM DEPTSEQ;