--CREATE
CREATE TABLE EMP_DDL (
    EMPNO NUMBER(4),
    ENAME VARCHAR(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7, 2),  --소수점 이하 두 자리를 포함한 7자리 숫자
    COMM NUMBER(7, 2),
    DEPTNO NUMBER(2)
    );
   
DESC EMP_DDL;

CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;

DESC DEPT_DDL;

--ALTER
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
    ADD HP VARCHAR(20);

ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;

ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

ALTER TABLE EMP_ALTER
    DROP COLUMN TEL;

--RENAME
RENAME EMP_ALTER TO EMP_RENAME;

--TRURNCATE
TRUNCATE TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;

--DROP
DROP TABLE EMP_RENAME;

--1
CREATE TABLE EMP_HW
    AS SELECT * FROM EMP WHERE 1 != 1;
   
SELECT *
FROM EMP_HW;

--2
ALTER TABLE EMP_HW
    ADD BIGO VARCHAR(20);

--3
ALTER TABLE EMP_HW
    MODIFY BIGO VARCHAR(30);

DESC EMP_HW;

--4
ALTER  TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;
   
--5
INSERT INTO EMP_HW (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
    SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL FROM EMP;

--6
DROP TABLE EMP_HW;