SELECT *
FROM EMP
WHERE DEPTNO = 30;

SELECT *
FROM EMP
WHERE EMPNO = 7782;

SELECT *
FROM EMP
WHERE EMPNO = 7499
    AND DEPTNO = 30;
   
SELECT *
FROM EMP
WHERE DEPTNO = 20
      OR JOB = 'SALESMAN';
  
SELECT *
FROM EMP
WHERE SAL >= 2500
    AND JOB = 'ANALYST';

--문자열도 대소 비교 가능! (알파벳 순서)
SELECT *
FROM EMP
WHERE ENAME >= 'F';

SELECT *
FROM EMP
WHERE NOT SAL = 3000;

SELECT *
FROM EMP
WHERE JOB NOT IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT *
FROM EMP
WHERE DEPTNO IN (10, 20);

    SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10
UNION
    SELECT EMPNO, ENAME, SAL
    FROM EMP
    WHERE DEPTNO = 20;
   
    SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10
UNION
    SELECT ENAME, EMPNO, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 20;

--1
SELECT *
FROM EMP
WHERE ENAME LIKE '%S';

--2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30
    AND JOB = 'SALESMAN';

--3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN (20, 30)
    AND SAL > 2000;

    SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO IN (20, 30)
INTERSECT
    SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
    WHERE SAL > 2000;

--4
SELECT *
FROM EMP
WHERE NOT (SAL >= 2000 AND SAL <= 3000);
   
--5
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30
    AND ENAME LIKE '%E%'
    AND SAL NOT BETWEEN 1000 AND 2000;

--6
SELECT *
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND JOB IN ('MANAGER', 'CLERK')
    AND ENAME NOT LIKE '_L%';