BEGIN
    DBMS_OUTPUT.PUT_LINE('Hello, PL/SQL');
END;

--1
DECLARE
    V_EMPNO NUMBER(4) := 7788;
    V_ENAME VARCHAR(10);
BEGIN
    V_ENAME := 'SCOTT';
    DBMS_OUTPUT.PUT_LINE('V_EMPNO : ' || V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('V_ENAME : ' || V_ENAME);
END;

--2
DECLARE
    V_TAX CONSTANT NUMBER(1) := 3;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_TAX : ' || V_TAX);
END;

--3
DECLARE
    V_DEPTNO NUMBER(2) DEFAULT 10;    
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);    
END;

--4
DECLARE
    V_DEPTNO NUMBER(2) NOT NULL := 10;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;

--5
DECLARE
    V_DEPTNO NUMBER(2) NOT NULL DEFAULT 10;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;

--6
DECLARE
    V_DEPTNO DEPT.DEPTNO%TYPE := 50;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : ' || V_DEPTNO);
END;

--7
DECLARE
    V_DEPT_ROW DEPT%ROWTYPE;
BEGIN
    SELECT DEPTNO, DNAME, LOC
    INTO V_DEPT_ROW
    FROM DEPT
    WHERE DEPTNO = 40;
    
    DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || V_DEPT_ROW.DEPTNO);
    DBMS_OUTPUT.PUT_LINE('DNAME : ' || V_DEPT_ROW.DNAME);
    DBMS_OUTPUT.PUT_LINE('LOC : ' || V_DEPT_ROW.LOC);
END;

--IF문
DECLARE
    V_NUMBER NUMBER := 13;
BEGIN
    IF MOD(V_NUMBER, 2) = 1 THEN
        DBMS_OUTPUT.PUT_LINE(V_NUMBER || '은(는) 홀수입니다.');
    END IF;
END;

DECLARE
    V_NUMBER NUMBER := 14;
BEGIN
    IF MOD(V_NUMBER, 2) = 1 THEN
        DBMS_OUTPUT.PUT_LINE(V_NUMBER || '은(는) 홀수입니다.');
    ELSE
        DBMS_OUTPUT.PUT_LINE(V_NUMBER || '은(는) 짝수입니다.');
    END IF;
END;

DECLARE
    V_SCORE NUMBER := 87;
BEGIN
    IF V_SCORE >= 90 THEN
        DBMS_OUTPUT.PUT_LINE('A');
    ELSIF V_SCORE >= 80 THEN
        DBMS_OUTPUT.PUT_LINE('B');
    ELSIF V_SCORE >= 70 THEN
        DBMS_OUTPUT.PUT_LINE('C');
    ELSIF V_SCORE >= 60 THEN
        DBMS_OUTPUT.PUT_LINE('D');
    ELSE
        DBMS_OUTPUT.PUT_LINE('F');
    END IF;
END;

--CASE문
DECLARE
    V_SCORE NUMBER := 87;
BEGIN
    CASE TRUNC(V_SCORE/10)
        WHEN 10 THEN DBMS_OUTPUT.PUT_LINE('A');
        WHEN 9 THEN DBMS_OUTPUT.PUT_LINE('A');
        WHEN 8 THEN DBMS_OUTPUT.PUT_LINE('B');
        WHEN 7 THEN DBMS_OUTPUT.PUT_LINE('C');
        WHEN 6 THEN DBMS_OUTPUT.PUT_LINE('D');
        ELSE DBMS_OUTPUT.PUT_LINE('F');
    END CASE;
END;

DECLARE
    V_SCORE NUMBER := 87;
BEGIN
    CASE
        WHEN V_SCORE >= 90 THEN DBMS_OUTPUT.PUT_LINE('A');
        WHEN V_SCORE >= 80 THEN DBMS_OUTPUT.PUT_LINE('B');
        WHEN V_SCORE >= 70 THEN DBMS_OUTPUT.PUT_LINE('C');
        WHEN V_SCORE >= 60 THEN DBMS_OUTPUT.PUT_LINE('D');
        ELSE DBMS_OUTPUT.PUT_LINE('F');
    END CASE;
END;

--반복문
DECLARE
    V_NUM NUMBER := 0;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('현재 숫자 : ' || V_NUM);
        V_NUM := V_NUM + 1;
        EXIT WHEN V_NUM > 4;
    END LOOP;
END;

DECLARE
    V_NUM NUMBER := 0;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('현재 숫자 : ' || V_NUM);
        V_NUM := V_NUM + 1;
        IF V_NUM > 4 THEN
            EXIT;
        END IF;
    END LOOP;
END;

DECLARE
    V_NUM NUMBER := 0;
BEGIN
    WHILE V_NUM <= 4 LOOP
        DBMS_OUTPUT.PUT_LINE('현재 숫자 : ' || V_NUM);
        V_NUM := V_NUM + 1;
    END LOOP;
END;

BEGIN
    FOR i IN 1..5 LOOP
        DBMS_OUTPUT.PUT_LINE('현재 i 값 : ' || i);
    END LOOP;
END;

BEGIN
    FOR i IN REVERSE 1..5 LOOP
        DBMS_OUTPUT.PUT_LINE('현재 i 값 : ' || i);
    END LOOP;
END;

BEGIN
    FOR i IN 1..5 LOOP
        CONTINUE WHEN MOD(i, 2) = 1;
        DBMS_OUTPUT.PUT_LINE('현재 i 값 : ' || i);
    END LOOP;
END;

--1
BEGIN
    FOR i IN 1..10 LOOP
        CONTINUE WHEN MOD(i, 2) = 0;
        DBMS_OUTPUT.PUT_LINE('현재 i의 값 : ' || i);
    END LOOP;
END;

--2
DECLARE
    V_DEPTNO DEPT.DEPTNO%TYPE := 10;
    V_DNAME DEPT.DNAME%TYPE;
BEGIN
    IF V_DEPTNO = 10 THEN
        V_DNAME := 'ACCOUNTING';
    ELSIF V_DEPTNO = 20 THEN
        V_DNAME := 'RESEARCH';
    ELSIF V_DEPTNO = 30 THEN
        V_DNAME := 'SALES';
    ELSIF V_DEPTNO = 40 THEN
        V_DNAME := 'OPERATIONS';
    ELSE
        V_DNAME := 'N/A';
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('DNAME : ' || V_DNAME);
END;

DECLARE
    V_DEPTNO DEPT.DEPTNO%TYPE := 20;
    V_DNAME DEPT.DNAME%TYPE;
BEGIN
    SELECT DNAME
    INTO V_DNAME
    FROM DEPT
    WHERE DEPTNO = V_DEPTNO;
    
    DBMS_OUTPUT.PUT_LINE('DNAME : ' || V_DNAME);
END;
